<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
		<TypeScriptToolsVersion>Latest</TypeScriptToolsVersion>
    <SpaRoot>..\openalprwebhookprocessor.client</SpaRoot>
    <SpaProxyLaunchCommand>npm start</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:4200</SpaProxyServerUrl>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <RootNamespace>OpenAlprWebhookProcessor</RootNamespace>
    <Version Condition="'$(GitVersion)' != ''">$(GitVersion)</Version>
    <Version Condition="'$(GitVersion)' == ''">1.0.0-dev</Version>
    <AssemblyVersion Condition="'$(GitAssemblyVersion)' != ''">$(GitAssemblyVersion)</AssemblyVersion>
    <AssemblyVersion Condition="'$(GitAssemblyVersion)' == ''">1.0.0.0</AssemblyVersion>
    <FileVersion Condition="'$(GitFileVersion)' != ''">$(GitFileVersion)</FileVersion>
    <FileVersion Condition="'$(GitFileVersion)' == ''">1.0.0.0</FileVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>CS8618</NoWarn>
    <UserSecretsId>4cca298b-24cc-40bb-bbdd-92b2fb978368</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="config\processor.db-shm" />
	  <None Remove="config\processor.db-wal" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="CoordinateSharp" Version="3.2.1.1" />
    <PackageReference Include="Flurl" Version="4.0.0" />
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="Lib.AspNetCore.WebPush" Version="2.2.2" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.7.0" />
    <PackageReference Include="Mediator.Abstractions" Version="3.0.*-*" />
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.*-*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
    <PackageReference Include="Microsoft.ML" Version="4.0.2" />
    <PackageReference Include="Microsoft.ML.FastTree" Version="4.0.2" />
    <PackageReference Include="Microsoft.ML.TimeSeries" Version="4.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
    <PackageReference Include="System.IO.Abstractions" Version="22.0.15" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="config\" />
		<Folder Include="Features\Users\Data\Repositories\" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="scripts\entrypoint.sh">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\openalprwebhookprocessor.client\openalprwebhookprocessor.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
	</ItemGroup>

</Project>
