name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: OpenAlprWebhookProcessor

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  windows-build-push:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Check out the repo
        uses: actions/checkout@main

      - name: Setup Buildx
        uses: actions/setup-dotnet@v1

      - name: Build Artifact
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="OpenAlprWebHookProcessor-${tag}-windows64"
          dotnet restore "OpenAlprWebhookProcessor.csproj"
          dotnet build "OpenAlprWebhookProcessor.csproj" -c Release
          dotnet publish "OpenAlprWebhookProcessor.csproj" -c Release -o "$release_name"
          tar czvf "${release_name}.tar.gz" "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "OpenAlprWebHookProcessor*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build-push:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Get git tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            mlapaglia/openalprwebhookprocessor:${{ steps.get_version.outputs.VERSION }}
            mlapaglia/openalprwebhookprocessor:latest